Auto-commit: Dockerfile.centos updated on 5/15/2026 2026-05-15T02:19:40.491Z

diff --git a/docker/ci-images/Dockerfile.centos b/docker/ci-images/Dockerfile.centos
--- a/docker/ci-images/Dockerfile.centos
+++ b/docker/ci-images/Dockerfile.centos
@@ -12,6 +12,10 @@ RUN set -eux; dnf -y install dnf-plugins-core || true
 RUN set -eux; dnf config-manager --set-enabled crb || true
 RUN set -eux; dnf -y install epel-release || true
 RUN set -eux; dnf -y update || true
+# nedded for otel module
+SHELL [ "/bin/bash", "--login", "-e", "-o", "pipefail", "-c" ]
+
+RUN bash [ "$width_otel" = "true" ] && dnf config-manager --set-enabled appstream && dnf -y install $width_otel_deps
 RUN set -eux; dnf -y install --allowerasing rpm-build rpmdevtools rpm-sign redhat-rpm-config gcc make curl mc \
  wget git gnupg2 cpio systemd createrepo_c pkgconf-pkg-config jq which krb5-devel rust cargo clang \
  zlib-devel pcre2-devel openssl-devel gd-devel libxslt-devel perl-devel perl-ExtUtils-Embed perl-macros \
